# Generated by Django 3.1.2 on 2020-10-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_id', models.CharField(max_length=20)),
                ('cert_no', models.CharField(max_length=20)),
                ('cert_name', models.CharField(max_length=20)),
                ('pub_data', models.DateField(db_column='insert_date', verbose_name='日期')),
            ],
            options={
                'verbose_name': '用户信息',
                'verbose_name_plural': '用户信息',
                'db_table': 'userinfo',
            },
        ),
    ]
