# Generated by Django 3.1.2 on 2020-10-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='pub_data',
            new_name='pub_date',
        ),
    ]
